### ISSUE TITLE
Timestamp computation for the HEAR benchmark

### ISSUE THREAD

**Issue by alexanderwerning** [nttcslab/msm-mae#2]
Hello,
whenever I try to evaluate on any of the two HEAR tasks that require timestamp embeddings (DCASE2016 Task 2, Maestro), I get a score of `NaN`. I believe the timestamp computation in the RuntimeMAE ist incorrect. In the HEAR API, the timestamps are defined in milliseconds, not seconds.
See for example in [hearbaseline/wav2vec2](https://github.com/hearbenchmark/hear-baseline/blob/main/hearbaseline/wav2vec2.py#L106), the timestamp values need to be multiplied by 1000. 

With this modification, I get reasonable results.

**Comment by daisukelab** [comment]
Hi @alexanderwerning,

Thank you for spotting the bug! We appreciate it. After fixing the bug, I confirmed the onset FMS result of 0.896 on DCASE2016 Task 2 using `80x512p16x16_paper/checkpoint-100.pth`, a good number expected for a single model.

```
predict - dcase2016_task2 - 2023-01-25 10:10:36,356 - 356 - Final Test Results: {"test": {"test_loss": 0.0164401363581419, "test_score": 0.8962472677230835, "test_event_onset_200ms_fms": 0.8962472677230835, "test_event_onset_200ms_fms_f_measure": 0.8962472677230835, "test_event
_onset_200ms_fms_precision": 0.937644362449646, "test_event_onset_200ms_fms_recall": 0.858350932598114, "test_segment_1s_er": 0.14847160875797272, "test_segment_1s_er_error_rate": 0.14847160875797272, "validation_score": 0.9464285969734192, "epoch": 100, "time_in_min": 9.736017
545064291},
```

I will commit my fix soon. Thanks again!
