### ISSUE TITLE
Assistance Requested for Printing Model Structure from pth File

### ISSUE THREAD

**Issue by yangyangshuyang** [nttcslab/msm-mae#7]
Hello,
I hope this message finds you well. I am currently working with the pth model structure you provided – specifically the "80*512p16*16_0425.pth" file. Unfortunately, I've encountered some challenges while attempting to print out its structure.

I was wondering if you might have encountered similar issues in your experience, or if you could suggest a more convenient method to print the entire structure of the model. Any guidance or assistance you could provide would be greatly appreciated.

Thank you very much for your time and help.

Best regards,

![image](https://github.com/nttcslab/msm-mae/assets/80260875/5192e294-b632-44d9-a9ee-c1d074cc56ce)
![image](https://github.com/nttcslab/msm-mae/assets/80260875/9cfc291f-de02-4816-a64a-65bbeb3ad32b)

**Comment by yangyangshuyang** [comment]
I just wanted to follow up on my earlier query regarding the issue I was facing with the model. I've managed to resolve the problem on my own. I appreciate the time and effort you put into maintaining this project and assisting users like myself. Sorry for any inconvenience my question might have caused. Thank you once again for your support!

Your code is good and complete, but I didn’t read it well before.

Best regards,

**Comment by daisukelab** [comment]
@yangyangshuyang Oh my... Please let me know anything I can help.
Thank you for your interest. I hope our code helps your project well!
